version: '3.8' # Updated version for better compatibility and features

services:
  db:
    image: postgres:17.0
    container_name: postgres_db # Assign a meaningful name for easy identification
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}        # Default to 'postgres' if not set
      POSTGRES_PASSWORD: ${DB_PASSWORD:-211004}     # Default to '211004' if not set
      POSTGRES_DB: mentalhealth                     # Database name is hardcoded
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Persistent volume for database data
    ports:
      - "${DB_PORT:-5432}:5432"                     # Default DB port, can be overridden
    networks:
      - app-network

  app:
    build:
      context: .                                    # Builds app from the current directory
    depends_on:
      - db                                          # Ensures 'db' starts before the app
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev} # Default to 'prod', can override
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST:-db}:${DB_PORT:-5432}/mentalhealth
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-211004}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost:3000,http://127.0.0.1:5500}
    ports:
      - "${APP_PORT:-8080}:8080"                    # Default app port, can be overridden
    volumes:
      - ./target:/app/target                        # Mounts the compiled app JARs
    command: >
      sh -c "java -jar /app/target/your-app.jar"    # Runs the Spring Boot app
    networks:
      - app-network

volumes:
  postgres_data:                                    # Persistent volume for the database

networks:
  app-network:
    driver: bridge                                  # Default network driver for app services