spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}
      file-size-threshold: ${FILE_SIZE_THRESHOLD:2KB}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: mental-health

  app:
    base-url: ${BASE_URL:http://localhost:8080}
    jwtSecret: ${JWT_SECRET}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      max-lifetime: 1800000


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  logging:
    level:
      org.springframework: ${SPRING_LOG_LEVEL:INFO}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  servlet:
    context-path: ${CONTEXT_PATH:/mental-health}

management:
  endpoints:
    web:
      exposure:
        include: health,info
    security:
      enabled: false

mvc:
  throw-exception-if-no-handler-found: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  url: ${CLOUDINARY_URL}

allowed:
  origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:5500}
scheduler:
  user-activity-cleanup-interval: ${SCHEDULER_USER_ACTIVITY_CLEANUP_INTERVAL:360000}  # default to 6 minutes (in milliseconds)
cache:
  duration:
    minutes: ${CACHE_DURATION_MINUTES:5}
context:
  path: ${CONTEXT_PATH:/mental-health}