spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:mentalhealth}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: true  # Set to true in production
    enabled: true
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  logging:
    level:
      org.springframework: WARN

allowed:
  origins: ${ALLOWED_ORIGINS:https://your-production-url.com}
