spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mentalhealth}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false  # Set to true in production
    enabled: true
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  logging:
    level:
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG

allowed:
  origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:5500}
